name: Docker build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: "Build and push the container"
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    uses: JuniorJPDJ/containers/.github/workflows/docker-parallel-multiarch-build.yml@master
    with:
      title: mau_mau_bot
      platforms: 'linux/amd64,linux/386,linux/arm/v7,linux/arm64'
      buildkit-mount-caches: '{"home-cache": "/root/.cache", "home-cargo": "/root/.cargo"}'
      buildkit-mount-cache-ids-append-platform: true
      registry: ghcr.io
      image-name: ${{ github.repository }}
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
